#!/bin/bash
while true; do
        current=$(mpc current)
            if [[ $db != "$current" ]]; then
                mpdnotify
                                db=$current
                                    fi
                                        sleep 1s
                                    done